### ISSUE TITLE
3D-RCAN Error in 5.2 Error mapping and quality metrics estimation with test images

### ISSUE THREAD

**Issue by skp13ms138** [HenriquesLab/ZeroCostDL4Mic#177]
After training the model, and inspection of loss function, Error mapping and quality metrics estimation was run using given test images from CARE(3D). It gave FileNotFoundError:
![Screenshot 2022-03-07 at 11 17 17](https://user-images.githubusercontent.com/49944850/157012371-0b96560f-3067-4681-b5cc-2e3b8c34ba10.png)

**Comment by guijacquemet** [comment]
Hi @skp13ms138 ,

Many thanks for reaching out! 
This error was caused by the h5py library that has been recently updated in Google Colab. I have now updated the notebook so that the right version of the library is used and it should fix the issue (works on my side). 
Please let me know if you are still having issues.

Cheers
Guillaume

**Comment by esgomezm** [comment]
I close the issue as I assume it's working well. Please reopen it in case you still get errors. Thank you!
